### ISSUE TITLE
Snapshot/epoch information and log files

### ISSUE THREAD

**Issue by akhanss** [ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018#11]
Hi @ZFTurbo ,
Thanks a lot for your great repo! You provided three pretrained models via this repo. Could you please mention steps of the snapshots? We noticed # '--snapshot', './snapshots/resnet101_oid_**189**.h5' code snippet in the 'retinanet_training_level_1/train_oid_level_1_resnet101.py' and # '--snapshot', './snapshots/resnet152_oid_**239**.h5' in the 'retinanet_training_level_1/train_oid_level_1_resnet152.py' file. So, are these snapshots of **189** and **239** respectively? However, you have shown a figure with  in the kaggle discusstion (https://www.kaggle.com/c/google-ai-open-images-object-detection-track/discussion/64633) with 271+ and 253+ epoch (or is it steps?). Also, you mentioned image size **728** - 1024 for ResNet50 and ResNet101 backbone; will it be **768** - 1024? I really appreciate if you could clarify theses minor information. In addition, it will greatly helpful if you could provide logs of the train and validation (my email is muhammedazamkhan@gmail.com, just in case)! Thank you very much.
Regards,
Azam

**Comment by ZFTurbo** [comment]
It was a bug with 728, it must be 768. I changed it in README. Thanks.

Step is some fixeds number of (images*batch_size) per epoch. It was ususally 10000 in my training.

You can find log for each model in files below.
[retinanet_resnet50_log.txt](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/files/3587419/retinanet_resnet50_log.txt)
[retinanet_resnet101_log.txt](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/files/3587420/retinanet_resnet101_log.txt)
[retinanet_resnet152_log.txt](https://github.com/ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018/files/3587421/retinanet_resnet152_log.txt)

**Comment by akhanss** [comment]
Thanks a lot for you kind and prompt reply. I noticed you mentioned that you had removed 'IsGroupOf' == 1 images. Is there any specific reason for this? I am just wondering if you have any performance issue for this action.

**Comment by ZFTurbo** [comment]
> 
> 
> I noticed you mentioned that you had removed 'IsGroupOf' == 1 images. Is there any specific reason for this? I am just wondering if you have any performance issue for this action.

I don't know if this action affect perofrmance. I think it wasn't necessary.

**Comment by akhanss** [comment]
Thanks a lot for your kind feedback, Keep your good work up!
