### ISSUE TITLE
How do you separate the class in five levels efficiently?

### ISSUE THREAD

**Issue by EvanAlbee** [ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018#14]
Hi ,I would like to know how did you get the result of line36 to line92(levels 1),line95 to line101(level2)
in `a00_utils_and_constants.py `
Did you do it by reading:
https://storage.googleapis.com/openimages/challenge_2018/bbox_labels_500_hierarchy_visualizer/circle.html and type it all by yourself or is there an efficient way (for example by coding) to do it ? 

Thanks!

**Comment by ZFTurbo** [comment]
As I remember I used label hierarchy JSON file and get this separation in semi-automatic way. I don't have complete function for it.

**Comment by EvanAlbee** [comment]
@ZFTurbo okay,thanks!
