### ISSUE TITLE
Issue in inference code for 500 classes

### ISSUE THREAD

**Issue by shahidost** [ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018#18]
Hello ZFTurbo,

The code is very perfect, I run the code for class level-1 and it's working perfectly. Bravo and thanks for the useful code.

Now I want to run the file: "**create_higher_level_predictions_from_level_1_predictions_csv.py**" for all level classes. 
But when I am running the file, it gives me the following .csv file error:
_FileNotFoundError: [Errno 2] No such file or directory: '/root/Keras-RetinaNet-for-Open-Images-Challenge-2018-master/input/challenge-2018-class-descriptions-500.csv'_ 

Did I miss to download the "**challenge-2018-class-descriptions-500.csv**" file?

I will be very thankful for your help.

regards,
shahi

**Comment by shahidost** [comment]
I download the file "**challenge-2018-class-descriptions-500.csv**"  and also .json file to run "create_higher_level_predictions_from_level_1_predictions_csv.py" file for all classes (i.e. pre-train models 2019) from your kaggle files but now I am having errors of two files:

1) retinanet_training_level_1.csv
2) retinanet_level_1_all_levels.csv

should I download these files from somewhere (or you will share) to run the file "**create_higher_level_predictions_from_level_1_predictions_csv.py**" file for all cases?

**Comment by ZFTurbo** [comment]
`retinanet_training_level_1.csv` - that's the file you need to give on input of script with predictions for LEVEL1 classes. e.g. you need to have it after inference of your set of images.

**Comment by shahidost** [comment]
Okay perfect. 
and what about the second file (i.e. retinanet_level_1_all_levels.csv).
Because I should also have to give the file path of that file?
I didn't train the model, I want to run the inference model only for my algorithm. 
Shahi

**Comment by ZFTurbo** [comment]
`retinanet_level_1_all_levels.csv` - it's the name of output file. It will be generated from this one: `retinanet_training_level_1.csv`

**Comment by shahidost** [comment]
Okay thanks, let me give a try. 

Thanks for your help and I really appreciate your effort and quick reply.
Shahi

**Comment by shahidost** [comment]
There is also one issue:
1) If I put **"class-descriptions-boxable.csv"** file into _"a00_utils_and_constants.py"_ it give me the error in inference file for class labels in line: **(_google_name = d2[google_name]_ **KeyError: 'Organ'**).** 
But if I updated the file "class-descriptions-boxable.csv" to "**challenge-2018-class-descriptions-500.csv**" it removes the error and generates the bounding box .csv file.

2) But, when I run the file: **"create_higher_level_predictions_from_level_1_predictions_csv.py"** it give me the error: ```
Traceback (most recent call last):
  File "create_higher_level_predictions_from_level_1_predictions_csv.py", line 90, in <module>
    return_only_new=True)
  File "create_higher_level_predictions_from_level_1_predictions_csv.py", line 58, in create_higher_level_classes_from_csv
    parents = get_parents_labels()
  File "/data/disk1/data/shahi/Keras-RetinaNet-for-Open-Images-Challenge-2018-master/a00_utils_and_constants.py", line 280, in get_parents_labels
    set_parents(parents, [nm], l, d1)
  File "/data/disk1/data/shahi/Keras-RetinaNet-for-Open-Images-Challenge-2018-master/a00_utils_and_constants.py", line 263, in set_parents
    nm = d1[k['LabelName']]
KeyError: '/m/02wmf'
```

If you can figure out where I am doing the error. 
Thanks!

**Comment by ZFTurbo** [comment]
Check which file has label '/m/02wmf' in it.

**Comment by shahidost** [comment]
**class-descriptions-boxable.csv** file has /m/02wmf (i.e. label=Flying disc).

**Comment by ZFTurbo** [comment]
Try to replace 'bbox_labels_600_hierarchy.json' with 'challenge-2018-label500-hierarchy.json' in get_parents_labels() function.

**Comment by ZFTurbo** [comment]
And use 'challenge-2018-class-descriptions-500.csv' instead of 'class-descriptions-boxable.csv'

**Comment by shahidost** [comment]
Okay, perfect thanks. I am looking for: "**challenge-2018-label500-hierarchy.json**" file but couldn't find it. Can you please share that file.

**Comment by shahidost** [comment]
If we look to all the classes of python file:**a00_utils_and_constants.py** there are total **595** classes (if I am not wrong) and when the code map it in the files: **bbox_labels_600_hierarchy.json** and  **class-descriptions-boxable.csv** there are **600 classes,** so I think _5 classes_ are missing in the **a00_utils_and_constants.py**.

These are my observations, maybe I am wrong. 

Thanks
Shahi

**Comment by shahidost** [comment]
I run the code for all classes after editing the file: **challenge-2018-label500-hierarchy.json** value: "Jaguar (Animal) to just "Jaguar". and inserting **"Flying disc"** into file: **a00_utils_and_constants.py** list: **LEVEL_1_LABELS** .
Thanks for your help ZFTurbo.
