### ISSUE TITLE
Detailed hyperparameters for training

### ISSUE THREAD

**Issue by dev-sungman** [ZFTurbo/Keras-RetinaNet-for-Open-Images-Challenge-2018#29]
Hi, thanks for your sharing. 

I found lr=1e-5, batch=1, single_gpu training in training scripts. 
However, in my opinion, this setting may not be optimal for large dataset (OID)
Can I ask you to share the detailed hyper-parameters for training OID?

**Comment by ZFTurbo** [comment]
As I remember I trained with this parameters. You can increase batch size according to GPU memory you have in your system. 
I trained on single GTX 1080 Ti with 11 GB.

**Comment by dev-sungman** [comment]
Thank you for your quick response!
